artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/376896ad168645de9d5a2c9f02ca9d5d/artifacts
end_time: 1755654682380
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 376896ad168645de9d5a2c9f02ca9d5d
run_name: thoughtful-sloth-742
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654682307
status: 3
tags: []
user_id: ahmedm4air
