artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/a5f321e438c24cabb55644b0bac7f563/artifacts
end_time: 1755613310046
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: a5f321e438c24cabb55644b0bac7f563
run_name: sincere-dove-124
source_name: ''
source_type: 4
source_version: ''
start_time: 1755613309779
status: 3
tags: []
user_id: ahmedm4air
