artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/6d1e0a10842a491cae073ca43aafd4e0/artifacts
end_time: 1755625763839
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 6d1e0a10842a491cae073ca43aafd4e0
run_name: intelligent-doe-231
source_name: ''
source_type: 4
source_version: ''
start_time: 1755625763570
status: 3
tags: []
user_id: ahmedm4air
