artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/aba32b76d717469ebd74b95f08eb63c1/artifacts
end_time: 1755659838302
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: aba32b76d717469ebd74b95f08eb63c1
run_name: wise-grouse-364
source_name: ''
source_type: 4
source_version: ''
start_time: 1755659838204
status: 3
tags: []
user_id: ahmedm4air
