artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/6eeb7f72d67d4e6cbaa3e9b556b8eec2/artifacts
end_time: 1755626778804
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 6eeb7f72d67d4e6cbaa3e9b556b8eec2
run_name: treasured-smelt-332
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626778724
status: 3
tags: []
user_id: ahmedm4air
