artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/11022d1857064e58a8fa1e24bc3e980d/artifacts
end_time: 1759513524151
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 11022d1857064e58a8fa1e24bc3e980d
run_name: spiffy-ant-504
source_name: ''
source_type: 4
source_version: ''
start_time: 1759513524103
status: 3
tags: []
user_id: ahmedsherif
