artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/cf340a91a10f4cbc85d2a523a5173220/artifacts
end_time: 1755627136110
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: cf340a91a10f4cbc85d2a523a5173220
run_name: industrious-grub-273
source_name: ''
source_type: 4
source_version: ''
start_time: 1755627136009
status: 3
tags: []
user_id: ahmedm4air
