artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/b38fa401f1794f7e9ca5c25763b87eab/artifacts
end_time: 1755635625213
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: b38fa401f1794f7e9ca5c25763b87eab
run_name: dashing-kite-779
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635625112
status: 3
tags: []
user_id: ahmedm4air
