artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/52fb2868aacb45fc88fba10497683f2f/artifacts
end_time: 1755481480022
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 52fb2868aacb45fc88fba10497683f2f
run_name: intrigued-bear-297
source_name: ''
source_type: 4
source_version: ''
start_time: 1755481479841
status: 3
tags: []
user_id: ahmedm4air
