artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/5360c31a7f324f60ba88ad4bc053440d/artifacts
end_time: 1755635584492
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 5360c31a7f324f60ba88ad4bc053440d
run_name: classy-goat-213
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635584394
status: 3
tags: []
user_id: ahmedm4air
