artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/204ec6fadab9439fb3ae60bbc28e2e6f/artifacts
end_time: 1755626300929
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 204ec6fadab9439fb3ae60bbc28e2e6f
run_name: nebulous-mule-915
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626300828
status: 3
tags: []
user_id: ahmedm4air
