artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/901c328ef9f04abbb9cb7069022725ed/artifacts
end_time: 1755627145173
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 901c328ef9f04abbb9cb7069022725ed
run_name: likeable-lynx-408
source_name: ''
source_type: 4
source_version: ''
start_time: 1755627145090
status: 3
tags: []
user_id: ahmedm4air
