artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/a72029cdf54d43618a6b863f5b47ce5c/artifacts
end_time: 1755655465683
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: a72029cdf54d43618a6b863f5b47ce5c
run_name: aged-goose-727
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655465589
status: 3
tags: []
user_id: ahmedm4air
