artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/bfdf6be3de0f44b58a96d1efd14f3347/artifacts
end_time: 1755658681525
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: bfdf6be3de0f44b58a96d1efd14f3347
run_name: wise-wren-107
source_name: ''
source_type: 4
source_version: ''
start_time: 1755658681435
status: 3
tags: []
user_id: ahmedm4air
