artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/c0a7b13ec3ac4c2b912558fba8509cb3/artifacts
end_time: 1755695849815
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: c0a7b13ec3ac4c2b912558fba8509cb3
run_name: colorful-sow-738
source_name: ''
source_type: 4
source_version: ''
start_time: 1755695849728
status: 3
tags: []
user_id: ahmedm4air
