artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/07321deffd34487aaca88e03d9dd316d/artifacts
end_time: 1755655514654
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 07321deffd34487aaca88e03d9dd316d
run_name: nervous-duck-321
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655514552
status: 3
tags: []
user_id: ahmedm4air
