artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/aa4765ab8b954b5384d048b24abc3e8e/artifacts
end_time: 1759511929768
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: aa4765ab8b954b5384d048b24abc3e8e
run_name: rogue-koi-534
source_name: ''
source_type: 4
source_version: ''
start_time: 1759511929728
status: 3
tags: []
user_id: ahmedsherif
