artifact_location: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303
creation_time: 1759500610084
experiment_id: '780825247749673303'
last_update_time: 1759500610084
lifecycle_stage: active
name: Text2SQL_Banking
