artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/375cd25e366441bba2d4bec89e1e0885/artifacts
end_time: 1755657788761
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 375cd25e366441bba2d4bec89e1e0885
run_name: rogue-smelt-53
source_name: ''
source_type: 4
source_version: ''
start_time: 1755657788454
status: 3
tags: []
user_id: ahmedm4air
