artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/042e416bcd1b43f79d95bd092db00986/artifacts
end_time: 1755481352855
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 042e416bcd1b43f79d95bd092db00986
run_name: indecisive-perch-741
source_name: ''
source_type: 4
source_version: ''
start_time: 1755481352602
status: 3
tags: []
user_id: ahmedm4air
