artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/d8d7f8b1c526463f99ac25d24a816a0e/artifacts
end_time: 1755654270653
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: d8d7f8b1c526463f99ac25d24a816a0e
run_name: tasteful-crane-605
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654270547
status: 3
tags: []
user_id: ahmedm4air
