artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/365f0556233c447bb5352a57ee90dc8c/artifacts
end_time: 1759511939580
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 365f0556233c447bb5352a57ee90dc8c
run_name: rare-fox-944
source_name: ''
source_type: 4
source_version: ''
start_time: 1759511939533
status: 3
tags: []
user_id: ahmedsherif
