artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/b061a3c8b56546c9b095208631b0e2ca/artifacts
end_time: 1755626993325
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: b061a3c8b56546c9b095208631b0e2ca
run_name: incongruous-bug-5
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626993263
status: 3
tags: []
user_id: ahmedm4air
