artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/35dea6dc58a4417abc54ad1bb56cea51/artifacts
end_time: 1755657849918
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 35dea6dc58a4417abc54ad1bb56cea51
run_name: victorious-duck-106
source_name: ''
source_type: 4
source_version: ''
start_time: 1755657849829
status: 3
tags: []
user_id: ahmedm4air
