artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/67dc937bf51644b880c43fedf67c8c57/artifacts
end_time: 1755654476577
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 67dc937bf51644b880c43fedf67c8c57
run_name: stylish-wasp-922
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654476483
status: 3
tags: []
user_id: ahmedm4air
