artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/c1707ead83484b6d961380a6e95fbcdf/artifacts
end_time: 1755659796785
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: c1707ead83484b6d961380a6e95fbcdf
run_name: sassy-conch-307
source_name: ''
source_type: 4
source_version: ''
start_time: 1755659796690
status: 3
tags: []
user_id: ahmedm4air
