artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/96929b29b6f54b9785ed5df4db971a26/artifacts
end_time: 1755626684026
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 96929b29b6f54b9785ed5df4db971a26
run_name: clumsy-bass-535
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626683940
status: 3
tags: []
user_id: ahmedm4air
