artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/88d4d5ef6a82406b8cee09afe7c31337/artifacts
end_time: 1755626181833
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 88d4d5ef6a82406b8cee09afe7c31337
run_name: luxuriant-calf-237
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626181744
status: 3
tags: []
user_id: ahmedm4air
