artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/f810f31e438c4197bb847bebc32ec3ae/artifacts
end_time: 1755654716446
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: f810f31e438c4197bb847bebc32ec3ae
run_name: rebellious-bee-755
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654716353
status: 3
tags: []
user_id: ahmedm4air
