artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/1c1c44bc13db4db39c7b6f3692b65d42/artifacts
end_time: 1755635738199
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 1c1c44bc13db4db39c7b6f3692b65d42
run_name: thundering-flea-79
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635737908
status: 3
tags: []
user_id: ahmedm4air
