artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/54f89d915cf74038b6df2418e9383ca3/artifacts
end_time: 1759502984672
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 54f89d915cf74038b6df2418e9383ca3
run_name: placid-flea-48
source_name: ''
source_type: 4
source_version: ''
start_time: 1759502984641
status: 3
tags: []
user_id: ahmedsherif
