artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/2824cac34cb94be0ab7856cb0fc959c8/artifacts
end_time: 1755655159108
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 2824cac34cb94be0ab7856cb0fc959c8
run_name: learned-cod-401
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655159018
status: 3
tags: []
user_id: ahmedm4air
