artifact_location: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660
creation_time: 1755480812159
experiment_id: '302908183335873660'
last_update_time: 1755480812159
lifecycle_stage: active
name: FIS_Text2SQL_Banking
