artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/91be03c34fbe4efe89b39c72c763c904/artifacts
end_time: 1755658932115
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 91be03c34fbe4efe89b39c72c763c904
run_name: thundering-snail-514
source_name: ''
source_type: 4
source_version: ''
start_time: 1755658932027
status: 3
tags: []
user_id: ahmedm4air
