artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/d73146cbf7084df1a5ee3d938031f7ba/artifacts
end_time: 1759513551684
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: d73146cbf7084df1a5ee3d938031f7ba
run_name: thoughtful-foal-693
source_name: ''
source_type: 4
source_version: ''
start_time: 1759513551638
status: 3
tags: []
user_id: ahmedsherif
