artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/41e1935a43b3423fb9e3e1a23bef1b9e/artifacts
end_time: 1755626795748
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 41e1935a43b3423fb9e3e1a23bef1b9e
run_name: brawny-carp-544
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626795647
status: 3
tags: []
user_id: ahmedm4air
