artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/aa8ceff12f7648dabc9b4f63eac81188/artifacts
end_time: 1755654705049
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: aa8ceff12f7648dabc9b4f63eac81188
run_name: funny-pig-115
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654704758
status: 3
tags: []
user_id: ahmedm4air
