artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/38ccecf51c8d46ebbfe1d85665b7e6e4/artifacts
end_time: 1755481639576
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 38ccecf51c8d46ebbfe1d85665b7e6e4
run_name: persistent-snipe-245
source_name: ''
source_type: 4
source_version: ''
start_time: 1755481631800
status: 3
tags: []
user_id: ahmedm4air
