artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/2110cf61cff040b19732ad2df0dda7d2/artifacts
end_time: 1755481189142
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 2110cf61cff040b19732ad2df0dda7d2
run_name: tasteful-toad-719
source_name: ''
source_type: 4
source_version: ''
start_time: 1755481189077
status: 3
tags: []
user_id: ahmedm4air
