artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/93c7b352b62c48f192c5aa7329e9532c/artifacts
end_time: 1759512835150
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 93c7b352b62c48f192c5aa7329e9532c
run_name: rebellious-carp-346
source_name: ''
source_type: 4
source_version: ''
start_time: 1759512835110
status: 3
tags: []
user_id: ahmedsherif
