artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/88e44225700f444eb60d22aafe712a22/artifacts
end_time: 1755626582105
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 88e44225700f444eb60d22aafe712a22
run_name: inquisitive-perch-70
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626582011
status: 3
tags: []
user_id: ahmedm4air
