artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/d15f1b24547742c686a38dd3e8bd312f/artifacts
end_time: 1755613331344
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: d15f1b24547742c686a38dd3e8bd312f
run_name: honorable-bug-777
source_name: ''
source_type: 4
source_version: ''
start_time: 1755613331247
status: 3
tags: []
user_id: ahmedm4air
