artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/fcafb8dfe2c44a969de261b8471dddb9/artifacts
end_time: 1755654522786
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: fcafb8dfe2c44a969de261b8471dddb9
run_name: nebulous-sponge-85
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654522592
status: 3
tags: []
user_id: ahmedm4air
