artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/bdb3ceab39d44ccda8e489c6945fab99/artifacts
end_time: 1755635789945
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: bdb3ceab39d44ccda8e489c6945fab99
run_name: merciful-shark-588
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635789842
status: 3
tags: []
user_id: ahmedm4air
