artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/e89c24219f8d4a24ba0a6291d1d19ed2/artifacts
end_time: 1755627186968
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: e89c24219f8d4a24ba0a6291d1d19ed2
run_name: puzzled-mole-631
source_name: ''
source_type: 4
source_version: ''
start_time: 1755627186861
status: 3
tags: []
user_id: ahmedm4air
