artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/b28fd4cfd0984ab3a93fd4e47e854ed9/artifacts
end_time: 1755635647712
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: b28fd4cfd0984ab3a93fd4e47e854ed9
run_name: selective-mink-350
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635647640
status: 3
tags: []
user_id: ahmedm4air
