artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/6b4a81d7fff64d6d8f182be4b30000ce/artifacts
end_time: 1759502913514
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 6b4a81d7fff64d6d8f182be4b30000ce
run_name: stately-dove-803
source_name: ''
source_type: 4
source_version: ''
start_time: 1759502913482
status: 3
tags: []
user_id: ahmedsherif
