artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/b098fd6a045d4f1d998e0b4316164f5d/artifacts
end_time: 1759512839295
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: b098fd6a045d4f1d998e0b4316164f5d
run_name: classy-skunk-984
source_name: ''
source_type: 4
source_version: ''
start_time: 1759512839244
status: 3
tags: []
user_id: ahmedsherif
