artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/e63096b188474f0abc0020973b74351a/artifacts
end_time: 1759514058473
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: e63096b188474f0abc0020973b74351a
run_name: fortunate-wolf-511
source_name: ''
source_type: 4
source_version: ''
start_time: 1759514058431
status: 3
tags: []
user_id: ahmedsherif
