artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/d8f007117cfe40dab971988779f6cf48/artifacts
end_time: 1755655231954
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: d8f007117cfe40dab971988779f6cf48
run_name: silent-stoat-84
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655231723
status: 3
tags: []
user_id: ahmedm4air
