artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/e4dfc9b39c8c4614849a1ab18d2d7340/artifacts
end_time: 1759513623563
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: e4dfc9b39c8c4614849a1ab18d2d7340
run_name: stylish-rat-377
source_name: ''
source_type: 4
source_version: ''
start_time: 1759513623532
status: 3
tags: []
user_id: ahmedsherif
