artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/0f6d692b06bb474aa65a5fdc5eb2f4b8/artifacts
end_time: 1759511700101
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 0f6d692b06bb474aa65a5fdc5eb2f4b8
run_name: dazzling-swan-869
source_name: ''
source_type: 4
source_version: ''
start_time: 1759511700062
status: 3
tags: []
user_id: ahmedsherif
