artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/7a7c390d8c254140a7204bd87fdbb291/artifacts
end_time: 1755654849027
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 7a7c390d8c254140a7204bd87fdbb291
run_name: bright-squirrel-532
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654848757
status: 3
tags: []
user_id: ahmedm4air
