artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/0f23f57b079047f2b385f7c64fada774/artifacts
end_time: 1755635776267
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 0f23f57b079047f2b385f7c64fada774
run_name: awesome-fish-733
source_name: ''
source_type: 4
source_version: ''
start_time: 1755635776071
status: 3
tags: []
user_id: ahmedm4air
