artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/c86c9281bab149cdb9124372b173107d/artifacts
end_time: 1759513970480
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: c86c9281bab149cdb9124372b173107d
run_name: painted-trout-20
source_name: ''
source_type: 4
source_version: ''
start_time: 1759513970449
status: 3
tags: []
user_id: ahmedsherif
