artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/27f5edf8f3c74ec6820bf0ff57324a76/artifacts
end_time: 1755655408702
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 27f5edf8f3c74ec6820bf0ff57324a76
run_name: sneaky-fawn-559
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655408604
status: 3
tags: []
user_id: ahmedm4air
