artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/6f365b6dc1c94796ac1e061330aae1de/artifacts
end_time: 1755654590382
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 6f365b6dc1c94796ac1e061330aae1de
run_name: bright-koi-983
source_name: ''
source_type: 4
source_version: ''
start_time: 1755654590287
status: 3
tags: []
user_id: ahmedm4air
