artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/c8a8b0dab06347349e6f5be0e37fc20d/artifacts
end_time: 1755655143096
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: c8a8b0dab06347349e6f5be0e37fc20d
run_name: useful-robin-537
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655143010
status: 3
tags: []
user_id: ahmedm4air
