artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/f103d9db6aae477a90d9a79cc3d6eb93/artifacts
end_time: 1755626130153
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: f103d9db6aae477a90d9a79cc3d6eb93
run_name: auspicious-gnat-964
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626129761
status: 3
tags: []
user_id: ahmedm4air
