artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/b434ba46591045eb90ac8565f2db2bd5/artifacts
end_time: 1755658890074
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: b434ba46591045eb90ac8565f2db2bd5
run_name: sedate-wasp-362
source_name: ''
source_type: 4
source_version: ''
start_time: 1755658889996
status: 3
tags: []
user_id: ahmedm4air
