artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/54e762547b0e4b2c9fcc2672d86a2709/artifacts
end_time: 1759514070141
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 54e762547b0e4b2c9fcc2672d86a2709
run_name: loud-frog-529
source_name: ''
source_type: 4
source_version: ''
start_time: 1759514070103
status: 3
tags: []
user_id: ahmedsherif
