artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/6413d9410c2a47eb924154c4dcb73dab/artifacts
end_time: 1759502926712
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: 6413d9410c2a47eb924154c4dcb73dab
run_name: salty-moth-258
source_name: ''
source_type: 4
source_version: ''
start_time: 1759502926668
status: 3
tags: []
user_id: ahmedsherif
