artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/79ed3fe0e02846cfa4d3ef5fa04e6f71/artifacts
end_time: 1755626839739
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 79ed3fe0e02846cfa4d3ef5fa04e6f71
run_name: amazing-dolphin-394
source_name: ''
source_type: 4
source_version: ''
start_time: 1755626839460
status: 3
tags: []
user_id: ahmedm4air
