artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/a9289f6d305e42a9a4226c2791bbdd30/artifacts
end_time: 1755655721665
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: a9289f6d305e42a9a4226c2791bbdd30
run_name: abrasive-swan-789
source_name: ''
source_type: 4
source_version: ''
start_time: 1755655721567
status: 3
tags: []
user_id: ahmedm4air
