artifact_location: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/0
creation_time: 1755480812153
experiment_id: '0'
last_update_time: 1755480812153
lifecycle_stage: active
name: Default
