artifact_uri: /Users/ahmedsherif/CW-POC-FIS-LENDERS-main/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/780825247749673303/b9e1ea6a2096466ab8a66a7aa6baf9f9/artifacts
end_time: 1759502944157
entry_point_name: ''
experiment_id: '780825247749673303'
lifecycle_stage: active
run_id: b9e1ea6a2096466ab8a66a7aa6baf9f9
run_name: judicious-goat-920
source_name: ''
source_type: 4
source_version: ''
start_time: 1759502944112
status: 3
tags: []
user_id: ahmedsherif
