artifact_uri: /Users/ahmedm4air/Documents/fis/dstoolkit-text2sql-and-imageprocessing/mlflow_tracking/302908183335873660/179ad22cbcec46b9ac6d5c22a24e3892/artifacts
end_time: 1755695812386
entry_point_name: ''
experiment_id: '302908183335873660'
lifecycle_stage: active
run_id: 179ad22cbcec46b9ac6d5c22a24e3892
run_name: upbeat-mule-74
source_name: ''
source_type: 4
source_version: ''
start_time: 1755695812293
status: 3
tags: []
user_id: ahmedm4air
